import { NextResponse } from 'next/server';

export const runtime = 'nodejs';

// Simulating a delay function to pretend agents are thinking.
const delay = (ms: number) => new Promise(res => setTimeout(res, ms));

export async function POST(req: Request) {
  const { prompt } = await req.json();

  const stream = new ReadableStream({
    async start(controller) {
      const encoder = new TextEncoder();
      const sendUpdate = (agentId: string, status: string, log: string, code?: string, url?: string) => {
        controller.enqueue(encoder.encode(`data: ${JSON.stringify({ agentId, status, log, code, url })}\n\n`));
      };

      try {
        // Agent 1: Project Orchestrator
        sendUpdate('1', 'active', 'Analyzing user intent and breaking down architecture...');
        await delay(2000);
        sendUpdate('1', 'done', 'Architecture Breakdown Complete. Delegating tasks to sub-agents.');

        // Agent 2: Research Agent
        sendUpdate('2', 'active', 'Scanning premium SaaS and high-end landing pages...');
        await delay(2500);
        sendUpdate('2', 'done', 'Extracted modern structure, minimalist whitespace patterns, and optimal user flows.');

        // Agent 3: Design Agent
        sendUpdate('3', 'active', 'Assembling global CSS tokens and Tailwind constraints...');
        await delay(2500);
        sendUpdate('3', 'done', 'UI/UX layout established. Mobile-first grid initialized.');

        // Agent 4: Build Engineer
        sendUpdate('4', 'active', 'Writing Next.js App Router components + Tailwind classes...');
        await delay(1500);
        
        // Simulating writing code chunk by chunk.
        const generatedCode = `
import React from 'react';
import { motion } from 'framer-motion';

export default function App() {
  return (
    <div className="min-h-screen bg-black text-white flex flex-col items-center justify-center">
      <motion.h1 
        initial={{ opacity: 0, scale: 0.9 }} 
        animate={{ opacity: 1, scale: 1 }} 
        className="text-6xl font-bold bg-gradient-to-r from-blue-500 to-teal-400 bg-clip-text text-transparent"
      >
        ${prompt || "Premium Digital Experience"}
      </motion.h1>
      <p className="mt-6 text-gray-400 max-w-lg text-center leading-relaxed font-light">
        A fully autonomous application generated by the Aura AI Engine.
      </p>
    </div>
  );
}
        `.trim();
        
        for (let i = 10; i <= generatedCode.length; i += 70) {
          sendUpdate('4', 'active', `Generating App component lines...`, generatedCode.substring(0, i));
          await delay(200);
        }

        sendUpdate('4', 'done', 'Application code generated flawlessly without syntax errors.', generatedCode);

        // Agent 5: QA / Debug Agent
        sendUpdate('5', 'active', 'Running ESLint, TypeScript validations, and visual DOM checks...');
        await delay(2000);
        sendUpdate('5', 'done', 'QA Passed. Code is strictly typed and responsive.');

        // Agent 6: Deployment Agent
        sendUpdate('6', 'active', 'Committing to automated GitHub repo & preparing Vercel build...');
        await delay(1500);
        sendUpdate('6', 'active', 'Vercel Deployment in progress: Resolving dependencies...', generatedCode);
        await delay(2000);
        
        // Output final URL.
        const mockUrl = "https://ai-builder-demo-project.vercel.app";
        sendUpdate('6', 'done', `Deployment Complete! Live at ${mockUrl}.`, generatedCode, mockUrl);

        controller.close();
      } catch (err) {
        controller.error(err);
      }
    }
  });

  return new NextResponse(stream, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache',
      'Connection': 'keep-alive',
    },
  });
}
