#!/usr/bin/env python3
"""Season first, then room category — The Chobe Safari Lodge and Nata Lodge, and the builder's grouped dropdowns.

    cd dt_library && python3 tools/season_room_layout.py

Docs (both APIs, both years, prices untouched):
    section title  = "<season> · <dates> — <room category>"      e.g. "2027/28 season · 01 Apr 2027 – 31 Mar 2028 — Luxury Room"
    row label      = "<room category> — <plan · nights · occupant>" e.g. "Luxury Room — Half board + two experiences · 2+ nights · Adult sharing"
  Labels stay unique within each doc and keep the room (the lodge page's booking form sends the label on its own).
  Extras are "Extras — <item>", packages "Packages — <package · plan · occupant>".
Builder (ddRateOptions, display only): a season group is split into room categories under a season heading when
  its rows carry a room segment; the earlier single-date-range fallback is removed (room grouping covers it).
Rollback copy: builder/index.html.bak_seasonroom
"""
import io, json, os, re, shutil, subprocess, tempfile
P = lambda f: os.path.join(os.getcwd(), f)
rd = lambda f: io.open(P(f), encoding='utf-8').read()
def wr(f, s, js=False):
    t = P(f) + ('.tmp.js' if js else '.tmp')
    io.open(t, 'w', encoding='utf-8').write(s)
    if js:
        subprocess.check_call(['node', '--check', t])
    os.replace(t, P(f))
MARK = 'CHOBE-NATA-SEASON-ROOM-LAYOUT'
SLUGS = ['chobe-safari-lodge', 'nata-lodge']
SEASON = {'2026': '2026/27 season · 01 Apr 2026 – 31 Mar 2027', '2027': '2027/28 season · 01 Apr 2027 – 31 Mar 2028'}
DATES = {'2026': '01 Apr 2026 – 31 Mar 2027', '2027': '01 Apr 2027 – 31 Mar 2028'}
NODE = r'''
const Module=require('module');const orig=Module._load;Module._load=function(r){if(/_ratesdb$/.test(r))return{dbConfigured:()=>false};return orig.apply(this,arguments);};
const path=require('path'),fs=require('fs');const o={};
for(const f of ['sto','rack']){const src=fs.readFileSync('api/'+f+'.js','utf8')+'\nmodule.exports.__D='+(f=='sto'?'DDS_STO_BY_YEAR':'DDS_RACK_BY_YEAR')+';';
const m=new Module('p');m.filename=path.resolve('api/p_'+f+'.js');m.paths=Module._nodeModulePaths(path.resolve('api'));m._compile(src,m.filename);
o[f]={};for(const s of ['chobe-safari-lodge','nata-lodge'])o[f][s]=m.exports.__D[s];}
console.log(JSON.stringify(o));'''
state = lambda: json.loads(subprocess.check_output(['node', '-e', NODE]))

def split(label, yr):
    """current tidied label -> (room category, detail)"""
    if label.startswith('Extras · '):
        left, d = label[len('Extras · '):].rsplit(' — ', 1)
        assert d == DATES[yr], label
        return 'Extras', left
    seg = label.split(' — ')
    assert len(seg) == 3, label
    room, detail, d = seg
    if d != DATES[yr]:                       # Secret Season package carries its own travel window
        assert room == 'Packages', label
        detail = detail + ' · travel ' + d
    return room, detail

before = state()
for f in ('sto', 'rack'):
    assert MARK not in rd('api/%s.js' % f)
NEW = {}
for f in ('sto', 'rack'):
    NEW[f] = {}
    for s in SLUGS:
        NEW[f][s] = {}
        for yr, d in before[f][s].items():
            order, by = [], {}
            for sec in d['sections']:
                for l, v in sec['rows']:
                    room, detail = split(l, yr)
                    if room not in by:
                        by[room] = []; order.append(room)
                    by[room].append([room + ' — ' + detail, v])
            secs = [{'title': SEASON[yr] + ' — ' + room, 'rows': by[room]} for room in order]
            labs = [r[0] for x in secs for r in x['rows']]
            assert len(labs) == len(set(labs)), (f, s, yr)
            assert [r[1] for x in secs for r in x['rows']] == sorted([r[1] for x in d['sections'] for r in x['rows']], key=lambda v: 0) or True
            assert sorted(v for x in secs for _, v in x['rows']) == sorted(v for x in d['sections'] for _, v in x['rows'])
            NEW[f][s][yr] = secs

block = '''
/* %s — season first, then room category, for The Chobe Safari Lodge and Nata Lodge (section titles "<season> — <room>", row labels "<room> — <detail>"). Sections only; prices and notes unchanged. Generated by tools/season_room_layout.py. */
(function chobeNataSeasonRoom%s() {
  var N = %s;
  var D = typeof %s === 'undefined' ? null : %s;
  if (!D) return;
  Object.keys(N).forEach(function (slug) {
    var e = D[slug]; if (!e) return;
    Object.keys(N[slug]).forEach(function (y) { if (e[y]) e[y].sections = N[slug][y]; });
  });
})();
'''
for f, dds in (('sto', 'DDS_STO_BY_YEAR'), ('rack', 'DDS_RACK_BY_YEAR')):
    wr('api/%s.js' % f, rd('api/%s.js' % f) + block % (MARK, f.capitalize(), json.dumps(NEW[f], ensure_ascii=False, indent=1), dds, dds), js=True)
after = state()
for f in ('sto', 'rack'):
    for s in SLUGS:
        assert sorted(after[f][s]) == sorted(before[f][s])
        for yr in before[f][s]:
            assert after[f][s][yr]['note'] == before[f][s][yr]['note']
            assert sorted(v for x in after[f][s][yr]['sections'] for _, v in x['rows']) == sorted(v for x in before[f][s][yr]['sections'] for _, v in x['rows'])

# index entries (labels unique within each doc, so the feeds' fold leaves them as they are)
def flat(d):
    out = []
    for sec in d['sections']:
        for l, v in sec['rows']:
            if not re.fullmatch(r'[\d,.]+', v):
                continue
            x = float(v.replace(',', ''))
            out.append({'n': l, 'p': int(x) if x == int(x) else x})
    return out
raw = rd('assets/rates-index.json'); data = json.loads(raw)
assert json.dumps(data, indent=0, ensure_ascii=False) == raw
snap = {x['name']: json.dumps(x, sort_keys=True, ensure_ascii=False) for x in data['lodges']}
NAMES = {'chobe-safari-lodge': 'The Chobe Safari Lodge', 'nata-lodge': 'Nata Lodge'}
for s, nm in NAMES.items():
    (e,) = [x for x in data['lodges'] if x['name'] == nm]
    e['rates'] = flat(after['sto'][s]['2026']); e['rack_2026'] = flat(after['rack'][s]['2026'])
    e['rates_2027'] = flat(after['sto'][s]['2027']); e['rack_2027'] = flat(after['rack'][s]['2027'])
changed = sorted(x['name'] for x in data['lodges'] if json.dumps(x, sort_keys=True, ensure_ascii=False) != snap[x['name']])
assert changed == sorted(NAMES.values()), changed
wr('assets/rates-index.json', json.dumps(data, indent=0, ensure_ascii=False))
print('docs restructured; index changed:', changed)

# builder: season heading, then room categories
F = 'builder/index.html'
b = rd(F)
m = re.search(r'\n  /\* one season covers most rows .*?\n  else\{', b, flags=re.S)
assert m, 'fallback block'
b = b[:m.start()] + '\n  else{' + b[m.end():]
OLD_PUSH = "    if(!by[g]){by[g]=[];groups.push(g);}by[g].push('<option '+r.attrs+'>'+r.html(t)+'</option>');});"
NEW_PUSH = "    if(!by[g]){by[g]=[];groups.push(g);}by[g].push({r:r,t:t});});"
OLD_RET = "  return groups.map(function(g){return '<optgroup label=\"'+ddHead(g)+'\">'+by[g].join('')+'</optgroup>';}).join('<option disabled value=\"\" class=\"ddgap\"></option>');\n}"
NEW_RET = """  var opt=function(it,t){return '<option '+it.r.attrs+'>'+it.r.html(t)+'</option>';};
  /* season first, then room category: inside a season group, rows whose text starts "<room> — " are split into room optgroups under a season heading */
  return groups.map(function(g){var items=by[g];
    if(mode==='season'&&g!=='Extras'&&g!=='Other rates'){var sub=[],sb={};items.forEach(function(it){var p=String(it.t).split(/\\s+—\\s+/);var rm=p.length>1?p[0]:'';it.rt=p.length>1?p.slice(1).filter(function(x){return x!==rm;}).join(' — '):it.t;if(!(rm in sb)){sb[rm]=[];sub.push(rm);}sb[rm].push(it);});
      if(sub.length>=2&&sub.every(function(x){return x;})&&items.length/sub.length>=1.6){return '<option disabled value="" class="ddgap ddseason">'+ddHead(g)+'</option>'+sub.map(function(rm){return '<optgroup label="'+esc(rm)+'">'+sb[rm].map(function(it){return opt(it,it.rt);}).join('')+'</optgroup>';}).join('');}}
    return '<optgroup label="'+ddHead(g)+'">'+items.map(function(it){return opt(it,it.t);}).join('')+'</optgroup>';}).join('<option disabled value="" class="ddgap"></option>');
}"""
assert b.count(OLD_PUSH) == 1 and b.count(OLD_RET) == 1
b = b.replace(OLD_PUSH, NEW_PUSH).replace(OLD_RET, NEW_RET)
for js in re.findall(r'<script(?![^>]*\bsrc=)[^>]*>(.*?)</script>', b, flags=re.S):
    if not js.strip():
        continue
    with tempfile.NamedTemporaryFile('w', suffix='.js', delete=False, encoding='utf-8') as t:
        t.write(js)
    try:
        subprocess.check_call(['node', '--check', t.name])
    finally:
        os.unlink(t.name)
if not os.path.exists(P(F + '.bak_seasonroom')):
    shutil.copy2(P(F), P(F + '.bak_seasonroom'))
wr(F, b)
print('builder: season -> room grouping')
