#!/usr/bin/env python3
"""Tidy the rate labels for The Chobe Safari Lodge and Nata Lodge so the builder's grouped dropdowns read cleanly,
and make the builder group a single-season lodge by room.

    cd dt_library && python3 tools/tidy_chobe_nata_labels.py

Label shape after this (segments split on ' — ', the way ddRateOptions reads them):
    <Room> — <plan · nights band · occupant> — <season dates>
    Campsite — <occupant · basis> — <season dates>
    Packages — <package · plan · occupant> — <dates>
    Extras · <item> — <season dates>                      (collected under one Extras heading)
Prices, sections, notes and years are unchanged; only labels move. Both APIs get the same labels.
Builder: when one season covers most of a lodge's rows (one rate-year sheet), those rows are grouped by
room instead of sitting in one big season group. Display only.
Rollback copy: builder/index.html.bak_ddroom
"""
import io, json, os, re, shutil, subprocess, tempfile
P = lambda f: os.path.join(os.getcwd(), f)
rd = lambda f: io.open(P(f), encoding='utf-8').read()
def wr(f, s, js=False):
    t = P(f) + ('.tmp.js' if js else '.tmp')
    io.open(t, 'w', encoding='utf-8').write(s)
    if js:
        subprocess.check_call(['node', '--check', t])
    os.replace(t, P(f))
MARK = 'CHOBE-NATA-TIDY-LABELS'
SLUGS = ['chobe-safari-lodge', 'nata-lodge']
NODE = r'''
const Module=require('module');const orig=Module._load;Module._load=function(r){if(/_ratesdb$/.test(r))return{dbConfigured:()=>false};return orig.apply(this,arguments);};
const path=require('path'),fs=require('fs');const o={};
for(const f of ['sto','rack']){const src=fs.readFileSync('api/'+f+'.js','utf8')+'\nmodule.exports.__D='+(f=='sto'?'DDS_STO_BY_YEAR':'DDS_RACK_BY_YEAR')+';';
const m=new Module('p');m.filename=path.resolve('api/p_'+f+'.js');m.paths=Module._nodeModulePaths(path.resolve('api'));m._compile(src,m.filename);
o[f]={};for(const s of ['chobe-safari-lodge','nata-lodge'])o[f][s]=m.exports.__D[s];}
console.log(JSON.stringify(o));'''
state = lambda: json.loads(subprocess.check_output(['node', '-e', NODE]))

ROOMS = ('Luxury Room', 'Suite', 'Explorer Suite', 'Accommodation')
def relabel(title, label):
    left, dates = label.rsplit(' — ', 1)
    p = left.split(' · ')
    if title.startswith(ROOMS):
        if title.startswith('Accommodation'):                       # Nata: one row per room type
            return 'Rooms — %s — %s' % (left, dates)
        room = p[0]
        if len(p) == 3:                                              # Chobe 2026: room · occ · plan
            return '%s — %s · %s — %s' % (room, p[2], p[1], dates)
        if len(p) == 4:                                              # Chobe 2027: room · occ · plan · band
            plan = 'All inclusive' if p[2] == 'All inclusive only' else p[2]
            return '%s — %s · %s · %s — %s' % (room, plan, p[3], p[1], dates)
        raise ValueError(label)
    if title.startswith('Campsite'):
        return 'Campsite — %s — %s' % (' · '.join(p[1:]), dates)
    if title.startswith('Package'):
        if 'whole package' in left:                                  # Chobe: name · occ · plan · basis
            return 'Packages — %s · %s · %s · per person for the whole stay — %s' % (p[0], p[2], p[1], dates)
        return 'Packages — %s — %s' % (left, dates)                  # Nata Makgadikgadi Special
    return 'Extras · %s — %s' % (left, dates)

before = state()
for f in ('sto', 'rack'):
    assert MARK not in rd('api/%s.js' % f)
MAP = {}                       # slug -> {old: new}, same for both feeds
for f in ('sto', 'rack'):
    for s in SLUGS:
        for y, d in before[f][s].items():
            for sec in d['sections']:
                for row in sec['rows']:
                    new = relabel(sec['title'], row[0])
                    assert MAP.setdefault(s, {}).get(row[0], new) == new
                    MAP[s][row[0]] = new
# uniqueness per slug/year/feed after relabel, dates kept, no digits in text values
for f in ('sto', 'rack'):
    for s in SLUGS:
        for y, d in before[f][s].items():
            labs = [MAP[s][r[0]] for sec in d['sections'] for r in sec['rows']]
            assert len(labs) == len(set(labs)), (f, s, y)
            for r in [r for sec in d['sections'] for r in sec['rows']]:
                assert r[0].rsplit(' — ', 1)[1] == MAP[s][r[0]].rsplit(' — ', 1)[1]

block = '''
/* %s — tidy labels for The Chobe Safari Lodge and Nata Lodge (room first, Extras and Packages grouped) so the builder's grouped dropdowns read cleanly. Labels only; prices unchanged. Generated by tools/tidy_chobe_nata_labels.py. */
(function chobeNataTidyLabels%s() {
  var M = %s;
  var D = typeof %s === 'undefined' ? null : %s;
  if (!D) return;
  Object.keys(M).forEach(function (slug) {
    var e = D[slug]; if (!e) return;
    Object.keys(e).forEach(function (y) {
      (e[y].sections || []).forEach(function (sec) {
        (sec.rows || []).forEach(function (r) { if (M[slug][r[0]]) r[0] = M[slug][r[0]]; });
      });
    });
  });
})();
'''
for f, dds in (('sto', 'DDS_STO_BY_YEAR'), ('rack', 'DDS_RACK_BY_YEAR')):
    wr('api/%s.js' % f, rd('api/%s.js' % f) + block % (MARK, f.capitalize(), json.dumps(MAP, ensure_ascii=False, indent=1), dds, dds), js=True)
after = state()
for f in ('sto', 'rack'):
    for s in SLUGS:
        assert sorted(after[f][s]) == sorted(before[f][s])
        for y in before[f][s]:
            a = [v for sec in after[f][s][y]['sections'] for l, v in sec['rows']]
            b = [v for sec in before[f][s][y]['sections'] for l, v in sec['rows']]
            assert a == b, (f, s, y)                                  # prices untouched, same order
            assert all(l in MAP[s].values() for sec in after[f][s][y]['sections'] for l, v in sec['rows'])

# index: same entries, new labels
def flat(d):
    out = []
    for sec in d['sections']:
        for l, v in sec['rows']:
            if not re.fullmatch(r'[\d,.]+', v):
                continue
            x = float(v.replace(',', ''))
            out.append({'n': l, 'p': int(x) if x == int(x) else x})
    return out
raw = rd('assets/rates-index.json'); data = json.loads(raw)
assert json.dumps(data, indent=0, ensure_ascii=False) == raw
snap = {x['name']: json.dumps(x, sort_keys=True, ensure_ascii=False) for x in data['lodges']}
NAMES = {'chobe-safari-lodge': 'The Chobe Safari Lodge', 'nata-lodge': 'Nata Lodge'}
for s, nm in NAMES.items():
    (e,) = [x for x in data['lodges'] if x['name'] == nm]
    e['rates'] = flat(after['sto'][s]['2026']); e['rack_2026'] = flat(after['rack'][s]['2026'])
    e['rates_2027'] = flat(after['sto'][s]['2027']); e['rack_2027'] = flat(after['rack'][s]['2027'])
changed = sorted(n for n in snap if json.dumps([x for x in data['lodges'] if x['name'] == n][0], sort_keys=True, ensure_ascii=False) != snap[n])
assert changed == sorted(NAMES.values()), changed
wr('assets/rates-index.json', json.dumps(data, indent=0, ensure_ascii=False))
print('labels tidied:', {s: len(m) for s, m in MAP.items()}, '| index changed:', changed)

# builder: single-season lodges group by room
F = 'builder/index.html'
b = rd(F)
assert 'one season covers' not in b
OLD = "  if(hit>=2&&hit>=rows.length*0.6){mode='season';}"
NEW = OLD + """
  /* one date-range season covers most rows (a single rate-year sheet, no named seasons): group those rows by room instead of one big season group */
  if(mode==='season'){var _cnt={},_top='',_n=0;key.forEach(function(k){if(k&&k.g!=='Extras'){_cnt[k.g]=(_cnt[k.g]||0)+1;_n++;if(!_top||_cnt[k.g]>_cnt[_top])_top=k.g;}});
    if(_top&&_cnt[_top]>=_n*0.7&&!String(_top).replace(/\\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\\.?/gi,'').replace(/[\\d\\s–\\-,.]/g,'')){key=key.map(function(k){if(!k||k.g!==_top)return k;var rs=String(k.rest).split(/\\s+—\\s+/);return rs.length>1?{g:rs[0],rest:rs.slice(1).join(' — ')}:k;});}}"""
assert b.count(OLD) == 1
b = b.replace(OLD, NEW)
for js in re.findall(r'<script(?![^>]*\bsrc=)[^>]*>(.*?)</script>', b, flags=re.S):
    if not js.strip():
        continue
    with tempfile.NamedTemporaryFile('w', suffix='.js', delete=False, encoding='utf-8') as t:
        t.write(js)
    try:
        subprocess.check_call(['node', '--check', t.name])
    finally:
        os.unlink(t.name)
if not os.path.exists(P(F + '.bak_ddroom')):
    shutil.copy2(P(F), P(F + '.bak_ddroom'))
wr(F, b)
print('builder: single-season room grouping added')
